@startuml
'https://plantuml.com/activity-diagram-beta

legend Odrestatus \nstatus 1: Ordre godkendt | status 2: bruger, stykliste, pris tildelt (pris+stykliste skjult fra bruger) | status 3: Carport godkendt af sælger | \nStatus 4: pris synlig for kunde| Status 5: Ordre betalt og godkendt af sælger |Status 6: Ordre logget i systemet, stykliste gives til kunde
skinparam BackgroundColor #f5f5f5
<style>
legend {
    BackgroundColor #f5f5f5
    FontColor black
    FontSize 20
}

Swimlane {
    FontSize 20
    FontStyle Bold
}

Note {
    FontColor black
}
</style>

|#LightGray|Kunde|
start
:Tilgå hjemmeside;
:Indtast egne mål for carport;
|Shop|
:Mål]
|Kunde|
if (skur?) is (ja) then
:indtast mål/placering for skur;
|Shop|
:Indstillinger for skur]
|Kunde|
else (nej)
|Shop|
:Intet skur]
endif
|Kunde|
:indtast kundeoplysninger;
|#lightgray|Shop|
:Lav visualisering;
|Kunde|
:visualisering]
:Godkend forespørgsel;
note
Status 1
end note
|Shop|
:forespørgsel]
:opret bruger;
:Lav stykliste;
:Udregn forslået pris;
:samle stykpris og stykliste i tilbud;
note
status 2
end note
:Send notifikation til sælger;
|#LightGray|Sælger|
:Notifikation]
:Tilgå carport;
note
odren låses så sælger ikke kan redigere i ordren
end note
if (problem?) is (ja) then
:Ring til kunde;
|Kunde|
:Opkald]
|Sælger|
:Rediger carport design;
endif;
|Sælger|
:godkend forespørgselsdata;
note
status 3
end note
|Shop|
:Opdater pris;
:Opdater stykliste;
|Sælger|
:Pris & stykliste]
if (Ændre i pris?) is (ja) then
|Shop|
:Opdater pris;
else (nej)
endif
:Send tilbud;
|Shop|
:Send email notifikation til kunde;
|Kunde|
:Tilbud]
note
status 4
end note
if (foretag køb) is (ja) then
|Sælger|
:Godkend køb;
note
status 5
end note
|Shop|
:Log data;
note
status 6
end note
|Sælger|
|Kunde|
:stykliste]
else (nej)
endif
stop

@enduml
