@startuml
'https://plantuml.com/activity-diagram-beta
skinparam BackgroundColor #f5f5f5
<style>
legend {
    BackgroundColor #f5f5f5
    FontColor black
    FontSize 20
}

Title {
    FontSize 40
}

Swimlane {
    FontSize 20
    FontStyle Bold
}
</style>

Title: AS-IS Aktivitetsdiagram


|Kunde|
start
:Tilgå hjemmeside;
:Indtast egne mål for carport;
|Shop|
:Mål]
|Kunde|
if (skur?) is (ja) then
:indtast mål/placering for skur;
|Shop|
:Indstillinger for skur]
|Kunde|
else (nej)
|Shop|
:Intet skur]
endif
|Kunde|
:Godkend forespørgsel;
|Shop|
:forespørgsel]
|Mail-system|
:Send mail til sælger inkl. Forespørgelsesdata;
|Sælger|
:Mail]
|Sælger|
:Indtast forespørgselsdata;
|Tilbudsberegner|
:Forespørgelsesdata]
|Sælger|
if (problem?) is (ja) then
:Ring til kunde;
|Kunde|
:Opkald]
|Sælger|
repeat
:Gennemgå ændringer med kunde;
|Kunde|
repeat while (godkend ændringer) is (nej)
-> ja;
else (nej)
endif
|Sælger|
:Indtast ændringer;
|Tilbudsberegner|
:Forspørgelsesdata]
|Sælger|
:Godkend data;
|Tilbudsberegner|
:Udregn tilbud;
|Sælger|
:Tilbud]
if (godkend tilbud) is (nej) then
:udregn nyt tilbud;
else (ja)
endif;
:Kontakt kunde;
|Mail-system|
:send mail;
|Kunde|
:Mail]
if (foretag køb) is (ja) then
|Sælger|
:Godkend køb;
|Tilbudsberegner|
:hent stykliste;
|Sælger|
:Lav ordrebekræftelse inkl. stykliste;
|Mail-system|
:Send ordrebekræftelse;
|Kunde|
:ordrebekræftelse inkl. stykliste]
else (nej)
endif
stop

@enduml
