@startuml
'https://plantuml.com/class-diagram

left to right direction

object Salesperson
object Customer
object Order
object Offer
object Carport
object CarportParts
object Shed


Salesperson -o Customer
Customer -o Order
Order -* Offer
Offer -* Carport
Order -* Carport
Carport -* CarportParts
Carport -o Shed

@enduml