@startuml
Title navigasionsdiagram
[*] --> frontpage
frontpage -> login
login ---> Customer
login -> signUp
login -> login : fejl login
login ---> Salesperson
frontpage -> designCarport
designCarport --> login
signUp --> login


state Salesperson{


frontpageSaleperson -> editItem
frontpageSaleperson --> allOrders
frontpageSaleperson ---> YourOrders
YourOrders -> orderDetails
orderDetails -> updateOrders
}

state Customer{

frontpageCustomer --> DesignCarport
frontpageCustomer -> orders
DesignCarport -> blueprint
blueprint --> receipt
blueprint --> orders
receipt -> orders
orders -> OrderDetails

}


@enduml